export interface Employee {
    name: string;
    jobTitle: string;
    age: number;
    nickname: string;
    isEmployee: boolean;
  }
  
  export const employees: Employee[] = [
    { name: "Giacomo Guilizzoni", jobTitle: "Founder & CEO", age: 40, nickname: "Peldi", isEmployee: true },
    { name: "Marco Botton", jobTitle: "Tuttofare", age: 38, nickname: "Botton", isEmployee: false },
    { name: "Mariah Maclachlan", jobTitle: "Better Half", age: 41, nickname: "Potato", isEmployee: true },
    { name: "Valerie Liberty", jobTitle: "Head Chef", age: 67, nickname: "Val", isEmployee: false },
    { name: "Eleanor Frost", jobTitle: "Ice Queen", age: 35, nickname: "Ellie", isEmployee: true },
    { name: "Lucian Sterling", jobTitle: "Chief Alchemist", age: 52, nickname: "Luc", isEmployee: false },
    { name: "Seraphina Dawn", jobTitle: "Morning Muse", age: 29, nickname: "Sera", isEmployee: true },
    { name: "Thorin Oakenshield", jobTitle: "Master Smith", age: 45, nickname: "Thor", isEmployee: false },
    { name: "Isadora Quinn", jobTitle: "Dream Weaver", age: 33, nickname: "Izzy", isEmployee: true },
    { name: "Cassian Holt", jobTitle: "Code Wizard", age: 39, nickname: "Cass", isEmployee: false },
    { name: "Liora Ember", jobTitle: "Flame Keeper", age: 27, nickname: "Lia", isEmployee: true },
    { name: "Magnus Vale", jobTitle: "Storyteller", age: 50, nickname: "Mag", isEmployee: false },
    { name: "Aurelia Stone", jobTitle: "Rock Star", age: 31, nickname: "Aura", isEmployee: true },
    { name: "Felix Marwood", jobTitle: "Wood Whisperer", age: 48, nickname: "Fel", isEmployee: false },
    { name: "Selene Night", jobTitle: "Moonlit Guide", age: 42, nickname: "Lena", isEmployee: true },
    { name: "Orion Blaze", jobTitle: "Star Chaser", age: 36, nickname: "Ori", isEmployee: false },
    { name: "Juniper Sage", jobTitle: "Herbalist", age: 30, nickname: "June", isEmployee: true },
    { name: "Caspian Wave", jobTitle: "Ocean Explorer", age: 44, nickname: "Cap", isEmployee: false },
    { name: "Marigold Sun", jobTitle: "Sunflower", age: 28, nickname: "Mari", isEmployee: true },
    { name: "Silas Thorn", jobTitle: "Thorn Protector", age: 53, nickname: "Si", isEmployee: false },
    { name: "Evangeline Mist", jobTitle: "Mist Maiden", age: 32, nickname: "Eva", isEmployee: true },
    { name: "Dorian Shade", jobTitle: "Shadow Dancer", age: 47, nickname: "Dory", isEmployee: false },
    { name: "Larkspur Bloom", jobTitle: "Flower Child", age: 26, nickname: "Lark", isEmployee: true },
    { name: "Roderick Iron", jobTitle: "Ironclad", age: 55, nickname: "Rod", isEmployee: false },
    { name: "Amara Light", jobTitle: "Beacon", age: 34, nickname: "Amy", isEmployee: true },
    { name: "Tiberius Storm", jobTitle: "Thunder Lord", age: 49, nickname: "Tib", isEmployee: false },
    { name: "Zinnia Petal", jobTitle: "Petal Pusher", age: 25, nickname: "Zin", isEmployee: true },
    { name: "Alaric Frost", jobTitle: "Frost Guardian", age: 51, nickname: "Al", isEmployee: false },
    { name: "Cressida Moon", jobTitle: "Lunar Priestess", age: 37, nickname: "Cress", isEmployee: true },
    { name: "Balthazar Gold", jobTitle: "Treasure Hunter", age: 46, nickname: "Balt", isEmployee: false },
    { name: "Elowen Sky", jobTitle: "Sky Watcher", age: 29, nickname: "Elo", isEmployee: true },
    { name: "Finnian River", jobTitle: "River Runner", age: 43, nickname: "Finn", isEmployee: false },
    { name: "Hazel Grove", jobTitle: "Tree Whisperer", age: 31, nickname: "Haze", isEmployee: true },
    { name: "Ignatius Flame", jobTitle: "Fire Starter", age: 54, nickname: "Iggy", isEmployee: false },
    { name: "Jasmine Breeze", jobTitle: "Wind Dancer", age: 28, nickname: "Jas", isEmployee: true },
    { name: "Kael Vortex", jobTitle: "Storm Spinner", age: 40, nickname: "Kael", isEmployee: false },
    { name: "Lyric Song", jobTitle: "Melody Maker", age: 33, nickname: "Lyr", isEmployee: true },
    { name: "Merek Steel", jobTitle: "Steel Forger", age: 56, nickname: "Mer", isEmployee: false },
    { name: "Niamh Dew", jobTitle: "Morning Dew", age: 27, nickname: "Nia", isEmployee: true },
    { name: "Oberon Tide", jobTitle: "Tide Master", age: 45, nickname: "Obe", isEmployee: false },
    { name: "Phaedra Glow", jobTitle: "Light Bringer", age: 30, nickname: "Phae", isEmployee: true },
    { name: "Quinton Ash", jobTitle: "Ash Collector", age: 48, nickname: "Quin", isEmployee: false },
    { name: "Rhea Dawn", jobTitle: "Dawn Herald", age: 32, nickname: "Rhea", isEmployee: true },
    { name: "Soren Cloud", jobTitle: "Cloud Shaper", age: 41, nickname: "Sor", isEmployee: false },
    { name: "Talia Mist", jobTitle: "Mist Weaver", age: 29, nickname: "Tal", isEmployee: true },
    { name: "Ulric Stone", jobTitle: "Stone Carver", age: 50, nickname: "Ulr", isEmployee: false },
    { name: "Vesper Night", jobTitle: "Evening Star", age: 35, nickname: "Ves", isEmployee: true },
    { name: "Wren Feather", jobTitle: "Feather Light", age: 26, nickname: "Wren", isEmployee: false },
    { name: "Xander Bolt", jobTitle: "Lightning Striker", age: 44, nickname: "Xan", isEmployee: true },
    { name: "Yara Bloom", jobTitle: "Blossom Keeper", age: 31, nickname: "Yar", isEmployee: false },
    { name: "Zephyr Wind", jobTitle: "Wind Rider", age: 39, nickname: "Zeph", isEmployee: true },
    { name: "Aisling Star", jobTitle: "Star Gazer", age: 28, nickname: "Ais", isEmployee: false },
    { name: "Bran Raven", jobTitle: "Raven Caller", age: 47, nickname: "Bran", isEmployee: true },
    { name: "Cora Flame", jobTitle: "Flame Dancer", age: 34, nickname: "Cor", isEmployee: false },
    { name: "Declan Oak", jobTitle: "Oak Warden", age: 52, nickname: "Dec", isEmployee: true },
    { name: "Elora Sun", jobTitle: "Sun Chaser", age: 30, nickname: "Elor", isEmployee: false },
    { name: "Frey Willow", jobTitle: "Willow Bender", age: 36, nickname: "Frey", isEmployee: true },
    { name: "Gideon Storm", jobTitle: "Storm Bringer", age: 49, nickname: "Gid", isEmployee: false },
    { name: "Hana Petal", jobTitle: "Petal Dancer", age: 27, nickname: "Han", isEmployee: true },
    { name: "Idris Shade", jobTitle: "Shade Walker", age: 45, nickname: "Idr", isEmployee: false },
  ];